#!/bin/sh /etc/rc.common
# Copyright (c) 2011-2012 OpenWrt.org
START=99

stop() {
    killall usbmuxd
}

start() {
    if [ ! -d "/var/lib/lockdown" ];then
        mkdir -p /var/lib/lockdown
    fi

    ./usr/sbin/usbmuxd &
}
